name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build and Push Image
      run: |
        IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/market-registry/market-app:${{ github.sha }}"
        echo "Using IMAGE=$IMAGE"
        docker build -t "$IMAGE" .
        docker push "$IMAGE"

    - name: Deploy to STAGING
      run: |
        IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/market-registry/market-app:${{ github.sha }}"
        gcloud run deploy market-forecast-staging \
          --image "$IMAGE" \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated

    - name: Health Check STAGING
      run: |
        echo "Waiting for staging to become healthy..."
        sleep 10
        curl -f https://market-forecast-staging-133361672503.us-central1.run.app/health

    - name: Deploy to PROD
      run: |
        IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/market-registry/market-app:${{ github.sha }}"
        gcloud run deploy market-forecast-prod \
          --image "$IMAGE" \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
